# default profile
spring:
  #profiles.active: dev
  application:
          name: price-service


# I18N (MessageSourceAutoConfiguration)
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8

# Infos Build
info.build:
  artifact: @project.artifactId@
  name: @project.name@
  description: @project.description@
  version: @project.version@

# Management
management:
  address: ${server.address}
  port: ${server.port}
  context-path: /manage

# Endpoints
endpoints.health:
  enabled: true
  sensitive: false

# SOAP
#soap:
#  wsdl: classpath:wsdl/TariffService_1.wsdl
#  server: http://productengine-int03:8080
#  path : promos/tariff/v2
#  servicename: Tarif
#  portname: TarifPort
#  namespace.uri: http://services.sbi.ch/system/productengine/tarif/v2
#  endpoint:
#    service: ${soap.server}/${soap.path}/${soap.servicename}


soap:
  wsdl: classpath:wsdl/TariffService_1.wsdl
  portname: TarifPort
  servicename: Tarif
  namespace: http://services.sbi.ch/system/productengine/tarif/v2
  endpoint:
    server: http://productengine-int03.hel.kko.ch:8080
    path: promos/tariff/v2
    url: ${soap.endpoint.server}/${soap.endpoint.path}
    service: ${soap.endpoint.url}/TariffService

# Logging
logging:
  level.: warn
  level.org.springframework.boot: WARN
  level.org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO




# Server
server:
  address: 127.0.0.1
  port: 8080

# Tomcat
  tomcat:
    max-http-header-size: 16380
    compression: on
    compressableMimeTypes: application/json,application/xml,text/html,text/xml,text/plain