# Database
spring:
  datasource:
    url: jdbc:h2:~/test;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

# Logging
logging:
  level.: info
  level.org.hibernate: debug




# dummy service for production confguration
info.product:
  basis:
    produktId : PRO_x0BAS__HEL_IG
    franchise : COD_Franchise_KVG-O_Erwachsener_300_HEL
    unfall : COD_ausgeschlossen_HEL
  top:
    produktId : PRO_Z1TOP__HEL_IG
    unfall : COD_ausgeschlossen_HEL
  primeo:
    produktId : PRO_Z1PRIM_HEL_IG
    unfall : COD_eingeschlossen_HEL
